package janken.visualComponents;

import javax.swing.SwingUtilities;

import janken.Main;

public class StartPanel extends javax.swing.JPanel {

	/**
	 * Creates new form StartPanel
	 */
	public StartPanel() {
		initComponents();
		jLabel1.setFont(Main.PIXEL_MPLUS_32);
		jTextArea2.setFont(Main.PIXEL_MPLUS_12);
		jButton1.setFont(Main.PIXEL_MPLUS_16);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jLabel1 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setBackground(new java.awt.Color(204, 204, 204));
		setLayout(new java.awt.GridBagLayout());

		jLabel1.setForeground(new java.awt.Color(51, 51, 51));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("感情的なじゃんけんゲーム");
		jLabel1.setToolTipText("");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
		add(jLabel1, gridBagConstraints);

		jScrollPane2.setBorder(null);

		jTextArea2.setEditable(false);
		jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
		jTextArea2.setColumns(20);
		jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
		jTextArea2.setLineWrap(true);
		jTextArea2.setRows(5);
		jTextArea2.setText("このゲームは、あなたの入力した文章を感情分析し、その結果からジャンケンの手を予測\nそして、ヒカキンさん、サザエさん、本田圭佑さんとジャンケンで勝負できるゲームです。\n\n勝利すると、ヒカキンさん、サザエさん、本田圭佑さんのおすすめの動画の情報を得ることが出来ます。");
		jTextArea2.setBorder(null);
		jTextArea2.setHighlighter(null);
		jTextArea2.setMinimumSize(new java.awt.Dimension(113, 50));
		jTextArea2.setName(""); // NOI18N
		jTextArea2.setPreferredSize(new java.awt.Dimension(212, 50));
		jScrollPane2.setViewportView(jTextArea2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(30, 20, 10, 20);
		add(jScrollPane2, gridBagConstraints);

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setIcon(new javax.swing.ImageIcon("./images/img_hikakin_start.png"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.33;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel2, gridBagConstraints);

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setIcon(new javax.swing.ImageIcon("./images/img_sazae_start.png"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.33;
		jPanel1.add(jLabel3, gridBagConstraints);

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setIcon(new javax.swing.ImageIcon("./images/img_keisuke_start.png"));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.weightx = 0.33;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(jLabel4, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weighty = 0.6;
		gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
		add(jPanel1, gridBagConstraints);

		jButton1.setBackground(new java.awt.Color(0, 153, 255));
		jButton1.setForeground(new java.awt.Color(51, 51, 51));
		jButton1.setText("Start");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 20, 15, 20);
		add(jButton1, gridBagConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		javax.swing.JPanel parent = (javax.swing.JPanel) SwingUtilities.getAncestorOfClass(javax.swing.JPanel.class, this);
		java.awt.CardLayout layout = (java.awt.CardLayout) parent.getLayout();
		layout.next(parent);
	}//GEN-LAST:event_jButton1ActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea2;
	// End of variables declaration//GEN-END:variables
}
